name: soma_facil
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  basic_utils: ^5.4.2
  brasil_fields: ^1.14.0
  cloud_firestore: ^4.8.5
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.7.3
  firebase_core: ^2.15.1
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.0.6+5
  intl: ^0.18.1
  image_picker: ^1.0.2
  image_cropper: ^5.0.0
  google_fonts: ^5.1.0
  google_sign_in: ^6.1.4
  google_mlkit_text_recognition: ^0.8.1
  mobx: ^2.2.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6 
  mobx_codegen: ^2.3.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
